/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CriandoObjs;
import com.sun.org.apache.xerces.internal.parsers.IntegratedParserConfiguration;
import javax.swing.JOptionPane;

/**
 *
 * @author Wilmar
 */
public class CriandoMGrupo extends javax.swing.JFrame {

    /**
     * Creates new form CriandoGrupo
     */
    ListadeGrupos janelaListadeGrupos;
    String nick;
    String raca;
    String classe;
    int ilvl;
    String funcao;
    CriandoObjs objetoPlayer;

    public CriandoMGrupo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nickTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fDps = new javax.swing.JRadioButton();
        fTank = new javax.swing.JRadioButton();
        fHealer = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        racaBox = new javax.swing.JComboBox<>();
        classeBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ilvlTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Função:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        nickTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nickTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Classe:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        buttonGroup1.add(fDps);
        fDps.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        fDps.setForeground(new java.awt.Color(250, 250, 250));
        fDps.setText("DPS");
        fDps.setOpaque(false);
        jPanel1.add(fDps, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        buttonGroup1.add(fTank);
        fTank.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        fTank.setForeground(new java.awt.Color(250, 250, 250));
        fTank.setText("Tank");
        fTank.setOpaque(false);
        fTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTankActionPerformed(evt);
            }
        });
        jPanel1.add(fTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        buttonGroup1.add(fHealer);
        fHealer.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        fHealer.setForeground(new java.awt.Color(250, 250, 250));
        fHealer.setText("Healer");
        fHealer.setOpaque(false);
        jPanel1.add(fHealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Nick:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        racaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Anão", "Elfo", "Gnomo" }));
        racaBox.setOpaque(false);
        jPanel1.add(racaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        classeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerreiro", "Caçador", "Mago", "Rogue", "Sacerdote", "Bruxo", "Paladino", "Druida", "Xamã" }));
        classeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classeBoxActionPerformed(evt);
            }
        });
        jPanel1.add(classeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 250, 250));
        jLabel6.setText("Item Lvl");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 250, 250));
        jLabel7.setText("Raça");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel1.add(ilvlTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ally.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classeBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        janelaListadeGrupos = new ListadeGrupos();
        janelaListadeGrupos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean marcado = false;
        boolean classeCorreta = true;
        nick = nickTextField.getText().trim();
        raca = racaBox.getSelectedItem().toString();
        classe = classeBox.getSelectedItem().toString();
        if(raca.equals("Gnomo") && (classe.equals("Paladino")||
                classe.equals("Druida")||classe.equals("Xamã"))){
            JOptionPane.showMessageDialog(null, "Não é possivel criar um Gnomo"
                    + " Paladino,Druida ou Xamã, escolha outra classe!");
            classeCorreta = false;
            
        }
        if(raca.equals("Elfo") && (classe.equals("Paladino")||
                classe.equals("Bruxo")||classe.equals("Xamã"))){
            JOptionPane.showMessageDialog(null, "Não é possivel criar um Elfo"
                    + " Paladino,Bruxo ou Xamã, escolha outra classe!");
            classeCorreta = false;
        }
        if(raca.equals("Humano") && (classe.equals("Druida")
                ||classe.equals("Xamã"))){
            JOptionPane.showMessageDialog(null, "Não é possivel criar um Humano"
                    + " Druida ou Xamã, escolha outra classe!");
            classeCorreta = false;
        }
        if(raca.equals("Anão") && (classe.equals("Druida"))){
            JOptionPane.showMessageDialog(null, "Não é possivel criar um Anão"
                    + " Druida, escolha outra classe!");
            classeCorreta = false;
        }        
        if (fHealer.isSelected()) {
            funcao = "Healer";
            marcado = true;
        } else if (fTank.isSelected()) {
            funcao = "Tank";
            marcado = true;
        } else {
            funcao = "Dps";
            marcado = true;
        }
        if(marcado && !nick.isEmpty() &&
                !ilvlTextField.getText().trim().isEmpty()&& classeCorreta) {
            ilvl = Integer.parseInt(ilvlTextField.getText().trim());
            objetoPlayer = new CriandoObjs();
            objetoPlayer.criarPlayer(nick, raca, classe, ilvl, funcao);
            nickTextField.setText("");
            ilvlTextField.setText("");
            JOptionPane.showMessageDialog(null, "Personagem Cadastrado!");
        }else{
            JOptionPane.showMessageDialog(null, "Confira os Dados Por Favor!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nickTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickTextFieldActionPerformed

    private void fTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriandoMGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriandoMGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriandoMGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriandoMGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriandoMGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> classeBox;
    private javax.swing.JRadioButton fDps;
    private javax.swing.JRadioButton fHealer;
    private javax.swing.JRadioButton fTank;
    private javax.swing.JTextField ilvlTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nickTextField;
    private javax.swing.JComboBox<String> racaBox;
    // End of variables declaration//GEN-END:variables
}
